# Generated by Django 2.0.5 on 2018-05-26 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('pk_adresse', models.AutoField(primary_key=True, serialize=False)),
                ('no_civique', models.CharField(max_length=30)),
                ('nom_rue', models.CharField(max_length=50)),
                ('code_postal', models.CharField(max_length=6)),
                ('ville', models.CharField(max_length=50)),
                ('pays', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'adresse',
                'verbose_name_plural': 'adresses',
                'db_table': 'adresse',
            },
        ),
        migrations.CreateModel(
            name='CarteCredit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_titulaire', models.CharField(max_length=100)),
                ('num_carte', models.CharField(max_length=100)),
                ('annee_expiration', models.CharField(max_length=2)),
                ('mois_expiration', models.CharField(max_length=2)),
                ('cvv', models.CharField(max_length=3)),
                ('date_emission', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('pk_client', models.AutoField(primary_key=True, serialize=False)),
                ('courriel', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=11)),
                ('type', models.CharField(choices=[('E', 'Entreprise'), ('P', 'Particulier')], max_length=1)),
                ('nom_particulier', models.CharField(blank=True, max_length=50, null=True)),
                ('prenom_particulier', models.CharField(blank=True, max_length=50, null=True)),
                ('sexe', models.CharField(blank=True, choices=[('H', 'Homme'), ('F', 'Femme'), ('A', 'Non défini')], max_length=1, null=True)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('nom_entreprise', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_entreprise', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solde', models.DecimalField(decimal_places=2, max_digits=10)),
                ('num_compte', models.CharField(max_length=8)),
                ('date_ouverture', models.DateTimeField(auto_now_add=True)),
                ('date_fermeture', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Courant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField()),
                ('etat', models.CharField(max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='adresse',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Client'),
        ),
    ]
