# Generated by Django 2.0.5 on 2018-06-14 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='id_transfert',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='trx',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.Transaction'),
        ),
        migrations.AlterField(
            model_name='adresse',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adresses', to='api.Client'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='compte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to='api.Compte'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type_transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.TypeTransaction'),
        ),
    ]
