# Generated by Django 2.0.5 on 2018-05-27 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0002_auto_20180526_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('pk_adresse', models.AutoField(primary_key=True, serialize=False)),
                ('no_civique', models.CharField(max_length=30)),
                ('nom_rue', models.CharField(max_length=50)),
                ('code_postal', models.CharField(max_length=6)),
                ('ville', models.CharField(max_length=50)),
                ('pays', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'adresse',
                'verbose_name_plural': 'adresses',
                'db_table': 'adresse',
            },
        ),
        migrations.CreateModel(
            name='CarteCredit',
            fields=[
                ('pk_carte_credit', models.AutoField(primary_key=True, serialize=False)),
                ('nom_titulaire', models.CharField(max_length=100)),
                ('num_carte', models.CharField(max_length=100, unique=True)),
                ('annee_expiration', models.CharField(max_length=2)),
                ('mois_expiration', models.CharField(max_length=2)),
                ('cvv', models.CharField(max_length=512)),
                ('date_emission', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cartecredit',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('pk_client', models.AutoField(primary_key=True, serialize=False)),
                ('courriel', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=11)),
                ('type', models.CharField(choices=[('E', 'Entreprise'), ('P', 'Particulier')], max_length=1)),
                ('nom_particulier', models.CharField(blank=True, max_length=50, null=True)),
                ('prenom_particulier', models.CharField(blank=True, max_length=50, null=True)),
                ('sexe', models.CharField(blank=True, choices=[('H', 'Homme'), ('F', 'Femme'), ('A', 'Non défini')], max_length=1, null=True)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('nom_entreprise', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_entreprise', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('pk_compte', models.AutoField(primary_key=True, serialize=False)),
                ('num_compte', models.CharField(max_length=8, unique=True)),
                ('solde', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_ouverture', models.DateTimeField(auto_now_add=True)),
                ('date_fermeture', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'compte',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('pk_transaction', models.AutoField(primary_key=True, serialize=False)),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(null=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('solde_avant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('solde_apres', models.DecimalField(decimal_places=2, max_digits=10)),
                ('etat', models.CharField(choices=[('ACC', 'Acceptée'), ('REF', 'Refusée'), ('GEL', 'Gelée')], max_length=3)),
            ],
            options={
                'db_table': 'transaction',
            },
        ),
        migrations.CreateModel(
            name='TypeTransaction',
            fields=[
                ('pk_type_transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'type_transaction',
            },
        ),
        migrations.CreateModel(
            name='Courant',
            fields=[
                ('compte_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='api.Compte')),
                ('pk_courant', models.AutoField(primary_key=True, serialize=False)),
                ('fk_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Client')),
            ],
            options={
                'db_table': 'courant',
            },
            bases=('api.compte',),
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('compte_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='api.Compte')),
                ('pk_credit', models.AutoField(primary_key=True, serialize=False)),
                ('limite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fk_carte_credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.CarteCredit')),
                ('fk_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Client')),
            ],
            options={
                'db_table': 'credit',
            },
            bases=('api.compte',),
        ),
        migrations.AddField(
            model_name='transaction',
            name='fk_compte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Compte'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='fk_transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Transaction'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='fk_type_transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.TypeTransaction'),
        ),
        migrations.AddField(
            model_name='adresse',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Client'),
        ),
    ]
