# Generated by Django 2.0.5 on 2018-06-05 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180526_2101'),
    ]

    operations = [
    ]
